apiVersion: v1
kind: Service
metadata:
  name: prism-era-web
  namespace: prism-era
  labels:
    app: prism-era-web
    app.kubernetes.io/name: prism-era-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: prism-era-web
---
apiVersion: v1
kind: Service
metadata:
  name: prism-era-api
  namespace: prism-era
  labels:
    app: prism-era-api
    app.kubernetes.io/name: prism-era-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: prism-era-api
